log:
  level: debug
  disable_sentry: true

db:
  url: postgresql://postgres:password@localhost:5432/postgres?sslmode=disable

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: Ordinals
  service_port: 80